#+TITLE: Amirrezaask Emacs configuration (a.k.a Hans)
#+AUTHOR: AmirrezaAsk
** Intro
I'm a huge fan of =HansZimmer=, so I call my emacs configuration =Hans=.
*** Important Note
However, this is not some form of an Emacs starter kit, it's simply my personal config with any quirks, 
so don't expect it to has all features like =doom= or =spacemacs=, or any features to be added.
** Why Not Emacs bundles ?
Emacs bundles like =doom= or =spacemacs= or any other one out there are amazing, they are a great way of learning how to organize Emacs configuration but they contain packages and
configurations that I might not use. Actually I used some ideas that I found in Doom-emacs and some configurations of several packages (`ivy` forexample) but I prefer my own configuration
since I know from ground up how I built it so it's much easier for me to add things or fix bugs if they happen.
** Ideas
=Hans= is built around some main ideas, some of them are not implemented yet.
+ First class support for Emacs keybindings.
+ Startup time matters a lot so it should always stay fast as possible.
+ Core should remain as simple as possible.
+ KISS (keep it simple stupid).
+ Modularity comes first .
+ No duplicate packages, focus on one (ex helm & ivy)
** Getting Started
#+BEGIN_SRC sh
# backup your existing .emacs.d
git clone git@gitlab.com:amirrezaask/hans.git ~/.emacs.d
cd ~/.emacs.d
make compile # only first time or after the updates
#+END_SRC
** Feature Highlight
*** Supported Languages
+ Assembly (MIPS, Haxor)
+ C/C++
+ Clojure
+ Common-Lisp
+ C#
+ Data formats (JSON, YAML, Proto, TOML)
+ Elixir
+ Emacs-lisp
+ F#
+ Go
+ Haskell
+ Java
+ Javascript
+ Kotlin
+ Lua
+ PHP
+ Python
+ Racket
+ Rust
+ Sh (sh scripts)
+ Typescript
+ Web (HTML/CSS)
*** Devops
+ Kuberenets interface
+ Docker interface
+ Ansible
*** Database Interface
+ SQL client (MYSql, PostgreSQL) [only emacs built in I improve them]
+ Mongo Client [TBA]
** Credits & Thanks 
+ =hlissner= (doom-emacs) creator for his amazing optimization ideas.
+ =R.M.S= (Richard Mathew Stallman) for creating =GNU= & =Emacs= the amazing platform we love to use.
+ Creator of all packages we use.
+ Emacs community.
